import {
  Area,
  AreaChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import { savingsTrend } from "../../data/mockAnalytics";

export function SavingsTrendChart() {
  return (
    <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-[var(--shadow-card)]">
      <h2 className="text-lg font-semibold text-slate-950">
        Procurement Savings Trend
      </h2>

      <p className="mt-1 text-sm text-slate-500">
        Monthly procurement savings generated by supplier matching and bundling.
      </p>

      <div className="mt-6 h-[320px]">
        <ResponsiveContainer width="100%" height="100%">
          <AreaChart data={savingsTrend}>
            <defs>
              <linearGradient
                id="savingsGradient"
                x1="0"
                y1="0"
                x2="0"
                y2="1"
              >
                <stop
                  offset="5%"
                  stopColor="#0f766e"
                  stopOpacity={0.35}
                />
                <stop
                  offset="95%"
                  stopColor="#0f766e"
                  stopOpacity={0}
                />
              </linearGradient>
            </defs>

            <CartesianGrid stroke="#e2e8f0" />

            <XAxis dataKey="month" />

            <YAxis />

            <Tooltip />

            <Area
              type="monotone"
              dataKey="savings"
              stroke="#0f766e"
              fill="url(#savingsGradient)"
              strokeWidth={3}
            />
          </AreaChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}
